[package]
name = "oxc-miette-derive"
version = "1.0.1"
authors = ["Boshen", "Kat Marchán <kzm@zkat.tech>"]
edition = "2018"
license = "Apache-2.0"
description = "Derive macros for miette. Like `thiserror` for Diagnostics."
repository = "https://github.com/zkat/miette"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = "2.0.85"
